### ISSUE TITLE
Randomize list order not just jump to random song? 

### ISSUE THREAD

**Issue by because-bot-fed** [kinsi55/BeatSaber_BetterSongList#13]
Hello - I'd really like to replace (or at least give it a try) the original SongBrowser plugin I was using, but the way Random works isn't working for me. 

When I hit random I'm not looking for a one-time random song suggestion but rather I'm looking to randomize the list and then work my way through that list 1-by-1, to achieve the same result I would need to hit the button each time. (And it just doesn't feel the same lol) 

Is there any way you could add an option/toggle so that the list order itself is randomized like SongBrowser was?

**Comment by kinsi55** [comment]
This is intentional as I personally do not necessarily see the need to randomize the order of songs (And doing that is also more resource intensitve than just jumping to a random position in the list).

I will eventually add an API so others can create custom sorts and filters that plug into Better Song List - But I have not figured out yet exactly how to cleanly achieve that.

In the mean time, to achieve a somewhat similar result, you can just switch to a different Sort that essentially makes it "random" like BeatSaver date or Song Length. Beyond that the only alternative I can offer you is [my other plugin Shaffuru](https://github.com/kinsi55/BeatSaber_Shaffuru#shaffuru) - Maybe thats even better than what you are looking for :D

**Comment by because-bot-fed** [comment]
Thank you :) Appreciate the response and the consideration.  I'll definitely check out that plugin :D
