### ISSUE TITLE
Sorting by NJS or Notes/s?

### ISSUE THREAD

**Issue by xJon** [kinsi55/BeatSaber_BetterSongList#26]
I'm not sure whether this is already a feature or not, but if it's not it'd be great to have similar sorting & filtering abilities for local maps as the great [BetterSongSearch](https://github.com/kinsi55/BeatSaber_BetterSongSearch#screenshots) mod made by someone successful.

**Comment by kinsi55** [comment]
Better Song List is never going to have sorting / filtering features nearly as extensive as Better Song Search does - Because thats what Better Song Search exists for (And because many people that use Better Song Search **never** touch the filters panel because they thing its "complicated" eventho I tried my best to make it as self explaining as possible).

I would argue that sorting by NPS is not really a useful metric to sort songs by as a 6 NPS map could very well be harder than an 8 NPS one, and neither is sorting by the NJS of the top or bottom diff because there could be difficulties in between that fall in the range of what you are looking for (Which you can target with the range filters in Better Song Search)

That being said, if somebody really wanted this, Better Song List is extensible, anybody can create a seperate plugin that adds any filter / sort they want to Better Song List, but I'm not going to clutter up the base plugin with sort methods that (imo) would not prove to be useful.

If at some point I figure out a decent way to implement #24 I could reconsider this because then the sorts would / could apply specifically to the difficulties marked in the playlist, but up until then it is a no, sorry.

**Comment by xJon** [comment]
I don't really understand "thats what Better Song Search exists for" as one of them is for to-be-downloaded maps and the other is for already-downloaded maps, but I understand the other reasons!

As you probably understood, I wanted some way of sorting by difficulty for my already downloaded songs; as I get better in the game I find that I enjoy more and more difficult maps but with no way to sort between them (excluding a manual playlist). This is a pretty basic feature in rhythm games such as osu! but alas Beat Saber has no universal difficulty rating per map.

**Comment by kinsi55** [comment]
The best metric we have to sort songs by in BeatSaber is usually the song BPM - Unfortunately we also have the issue tho that mappers most of the time map at half the song BPM, so you could have a 150 BPM map thats actually 150 BPM, or one that is actually 300.

The next best metric we have is **S**PS, as in, Swings per second. Unfortunately however, this is rather complicated to calculate.
One could certainly make a custom sorter for Better Song List which does all of the calculation necessary to accomplish that, but I dont think that someone is going to be me.

> I don't really understand "thats what Better Song Search exists for" as one of them is for to-be-downloaded maps and the other is for already-downloaded maps, but I understand the other reasons!

You can use Better Song Search for browsing only downloaded songs as well (As there is a filter for that) - I created Better Song List after I did Better Song Search, and it was always intended to be the simpler, "smaller brother" of it.

**Comment by xJon** [comment]
Thank you for the detailed response :) In which case I'll probably try to use Better Song Search for local maps, although if someone does end up making a custom sorter by difficulty it'd be ideal and awesome.
