### ISSUE TITLE
Enhancement: Sort by upvotes

### ISSUE THREAD

**Issue by JamDaBam** [kinsi55/BeatSaber_BetterSongList#27]
This Mod is so clearly structured but it lacks ofthe sort method by upvotes like the SongBrowser Plugin.
I would fully switched if this sort method would be implemented.

Amazing Job.
Thanks for your mod.

**Comment by kinsi55** [comment]
Sorting by Upvotes is not a builtin Method because to me it is virtually useless (And I try to not clutter UI wherever possible). All the older maps, despite many of them being awful, have very inflated upvotes (and thus ratings) so this is not something I'll be shipping with the base plugin. If somebody else wanted, you can add your own sort / filter methods into BSL with a seperate plugin - I believe there even is a seperate plugin adding many sort / filter methods that I dont include, couldnt tell you the name tho.
