### ISSUE TITLE
0.3.7 doesn't show custom sorters

### ISSUE THREAD

**Issue by nanikit** [kinsi55/BeatSaber_BetterSongList#29]
I think `FilterUI.persistentNuts.UpdateTransformerOptionsAndDropdowns();` should be inserted at [this](https://github.com/kinsi55/BeatSaber_BetterSongList/blob/41b3fd8808ee3fa2bfe6cbd0e9029e73ce3ec5f0/Sorters/SortMethods.cs#L113).

Apart from the above I saw that Plugin.cs references the  `SharedCoroutineStarter.Init()`, so it looks like the master branch is partially pushed.

Also apart from the above, I'm seeing error that [starsBeatleader](https://github.com/kinsi55/BeatSaber_BetterSongList/blob/41b3fd8808ee3fa2bfe6cbd0e9029e73ce3ec5f0/HarmonyPatches/UI/ExtraLevelParams.cs#L125) does not exist. This type is from SongDetailsCache, could you check it?

**Comment by kinsi55** [comment]
As for the last point, update songdetails

**Comment by nanikit** [comment]
Can you provide an update on this issue? It appears to be replicable with BS 1.34.2 and BetterSongList v0.3.9 from beatmods. However I'm uncertain about its reliability since it seems to work intermittently.

I want to release a custom sorter on beatmods, but the uncertain registration is holding me back. Would it be advisable to invoke the internal `persistentNuts.UpdateTransformerOptionsAndDropdowns`?

**Comment by kinsi55** [comment]
Sorry for essentially ignoring this, the truth is that I'm not only kinda demotivated about BS modding in general but also dont really care too much about supporting the latest version currently because 1.29.1 is considered the "main version" and is used by most. Just from the description debugging this (And fixing it in a non-hacky way) seems like a pain.

With this working fine in 1.29.1 and me not having changed anything whatsoever in regards to this I'll just have to assume its a regression in BSML. `UpdateTransformerOptionsAndDropdowns()` is already called "all the time" when a category or collection is selected, so that probably wouldnt fix anything.

**Comment by nanikit** [comment]
Thanks for quick response. Then I guess the way to go is using the hacky way in my plugin.

I understand if you're feeling demotivated. I think modding is hard work with little reward, but thanks for sticking with it.

**Comment by kinsi55** [comment]
What is the "hacky way" ?

**Comment by kinsi55** [comment]
And you're saying you do not need to do that in 1.29.1?

**Comment by nanikit** [comment]
> And you're saying you do not need to do that in 1.29.1?

Yeah.

I've just tested with BS 1.29.1 with BetterSongList v0.3.3. There was no problem with that version.
